### ISSUE TITLE
Make sure handler buffer is actually not in buffer pool structure as free buffer

### ISSUE THREAD

**Issue by sosterwalder** [concretecloud/chirp#11]
In the method `ch_bf_return` in the file `buffer.h` the usage of given handler buffer
is first set to zero, then the number of used buffers is decreased by one and finally the
buffer is (re-)added to the free buffers of the pool.

Maybe an assertion should be made at the beginning of the method, that the given
handler buffer actually is not in the list of free buffers of the pool?

**Comment by ganwell** [comment]
#145 will close this
