### ISSUE TITLE
Make log messages consistent

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#117]
Should look like this

```cpp
"Read message with id: %s, serial:%s from %s:%d type:%d data_len:%d, data:%s ch_chirp_t:%p, ch_connection_t:%p, ",
```
* What happended
* First important identifiers other than pointers
* Information about the event
* Objects (pointers) the event is related to: ordered from general to specific

It seems like the first three rules are quite consistent, but the pointer are currently sometimes in the wrong order.

**Comment by winged** [comment]
As discussed: closing
