### ISSUE TITLE
Use indirect connection references (via ch_remote_t)

### ISSUE THREAD

**Issue by winged** [concretecloud/chirp#136]
Never reference ch_connection_t directly, always use it "boxed" within ch_remote_t

**Comment by ganwell** [comment]
Always was IMO to broad the important function is

```c
int
ch_wr_process_queues(ch_remote_t* remote)
```

I also think that if this applies to write callbacks it is a bug in either chirp or libuv. Since closed connections should not generate callbacks. Therefore I consider this closed.
