### ISSUE TITLE
Replace retry by a ping message if we are near gc-timeout

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#210]
If a connection is near gc-timeout (lets say 2/3+ of the gc-time), we could send a ping message, before the real message: this would get rid of retries and all the message deduplication logic.

(delete receipt data types and retry  fields from code)

**Comment by winged** [comment]
Wouldn't this act kind of like a keepalive, thus never allowing the connection to be GC'd?

**Comment by ganwell** [comment]
@winged The key is "before the real message". We would only send a ping message, when the user wanted to send a message. So no it is not like a keep-alive. The ping message, then may or may not fail (it gets ignored anyway). When the real message is sent, chirp already closed the connection or everything is ok. Either way the second message will never fail because of gc.

**Comment by winged** [comment]
Ah, now I understand. However, you'd still have to do the whole retry stuff, as there are other reasons for the connection to fail. There could still be network outage, or the connection being GC'd on the peer's side just in the wrong moment etc..

If I understand the situation correctly, you would still need to do the retry in that case

**Comment by ganwell** [comment]
@winged yes, but these are not introduced by libchirp, so we can delegate it to application, which is as we leaned from erlang the way to go. I think I also solved DoS problem wihtout adding complexity to chirp (PRs are comming). I want to keep it simple simple simple. All the libuv/TLS boiler-plate and error handling is complex enough.

**Comment by ganwell** [comment]
Implemented in #242
