### ISSUE TITLE
Security: Allow to define a list of trusted (server) nodes

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#250]
The current security model embraces the peer to peer nature of chirp: a key signed with the ca-cert means a node is a 100% equal partner. It absolutely possible to build a client-server network with chirp, but the security settings don't allow to that. This can be solved by defining a list of fingerprints of trusted server/broker nodes.

`config.TRUSTED_NODES = { "fingerprint1", "fingerprint2", ..., 0}`

Clients will only connect to these nodes. Fingerprints are fingerprints of the peer client-cert.

**Comment by ganwell** [comment]
@winged @keachi any comments?

**Comment by ganwell** [comment]
Actually I think its better to configure this dynamically:

* ch_chirp_add_trusted_node(char *);
* ch_chirp_del_trusted_node(char *);

**Comment by winged** [comment]
Maybe we should instead think about (optionally) use the OS's CA infrastructure (Check if client's cert is signed by a known CA via `/etc/ssl/certs/*` or similar.. Maybe OpenSSL already has infra for this kind of query?

**Comment by ganwell** [comment]
@winged That is no solution to the problem. I call to explain.

**Comment by ganwell** [comment]
Superseded by #255
