### ISSUE TITLE
Move to AGPL

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#274]
@winged @sosterwalder @keachi 

I want to switch to AGPL, not that it matters for the project, it's more a statement. I am currently moving all code I can to AGPL, because of recent events in the "cloud".

Please answer in that issue whether you agree or not.

**Comment by winged** [comment]
Fine for me

**Comment by keachi** [comment]
Hi @ganwell 
That's fine for me. Thanks for asking.

**Comment by ganwell** [comment]
Done
