### ISSUE TITLE
Fix macOS build on Travis CI

### ISSUE THREAD

**Issue by sosterwalder** [concretecloud/chirp#28]
Currently the macOS build fails:

```
env: python3: No such file or directory
The command "./ci/osx.sh" exited with 127.
```

Probably it is enough to change the script from using `python3` to use `python` instead.

**Comment by sosterwalder** [comment]
The error is most likely coming from

https://github.com/concretecloud/chirp/blob/master/configure#L1

**Comment by ganwell** [comment]
@sosterwalder IMO python3 is correct. I want to use python3. I merged your fix. Can we close?

**Comment by sosterwalder** [comment]
Yes, 15e786a and d25537c seem to fix it.
