### ISSUE TITLE
Writer: Implement retries, make configurable

### ISSUE THREAD

**Issue by sosterwalder** [concretecloud/chirp#36]
The number of retries when reaching a timeout when sending is currently set to zero:

```
    tmp_err = uv_timer_start(
        &writer->send_timeout,
        _ch_wr_send_timeout_cb,
        ichirp->config.TIMEOUT * 1000,
        0
    );
```

The comment of this method stated 

> Will retry sending n-times according to config.

although. 

Is zero intended or is it planned to make the number of retries configurable?

**Comment by ganwell** [comment]
Well this has nothing to do with uv_timer_start. But this has to be implemented.

**Comment by ganwell** [comment]
Close: too wrong
