### ISSUE TITLE
Discuss license

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#85]
At the moment the license is AGPL, with the idea to protect against hostile takeovers of the project. Which of course LGPL would do too. Only MIT/BSD/ICS style licenses allow hostile takeovers. So we should probably consider to switch to LGPL, because AGPL doesn't make much sense for a library that has to go into many ecosystems, definitely:

* chirp-node
* chirp-python
* chirp-go
* chirp-php

Hopefully:

* chirp-ruby
* chrip-rust
* chirp-lua
* chirp-haskell

Meh:

* chirp-java
* chirp-dotnet
* chirp-cpp

Can we do all these with LGPL? I actually like BSD but I don't like the hostile takeovers.

Hostile takeover: Fork a BSD project with LGPL license, so they cannot merge things back.

**Comment by ganwell** [comment]
@eni23

**Comment by keachi** [comment]
LGPL will do it for me. I like LGPL for libraries.

**Comment by sliverc** [comment]
I would prefer LGPL as well. This would allow library to be dynamically linked in commercial products though. Question is whether this is desirable?

**Comment by ganwell** [comment]
I definitely want commercial products. The only fear I have is that someone takes chirp converts it to yet another bloated message-queue and all the attention from the clean and simple version is gone. While if use a BSD license, we might not even be allow the take security patches from the fork. So we are totally screwed.
