### ISSUE TITLE
Generate and serve the docs on 1042.ch

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#9]
* Pull every night
* Build if something was updated

!Important use simple and lightweight way to detect if pull changed something (shell script comparing HEAD revision)

`git rev-parse HEAD`

**Comment by sosterwalder** [comment]
Implemented a python script, that gets the current HEAD rev., pulls the current master-branch, gets the new HEAD rev. and compares the two revs. If they differ the documentation is (re-) built.

This script gets run every night at about 3 o' clock.

The documentation is served here: [https://1042.ch/chirp/](https://1042.ch/chirp/).

**Comment by ganwell** [comment]
@sosterwalder  JUHUIII
