### ISSUE TITLE
Branding?

### ISSUE THREAD

**Issue by ganwell** [concretecloud/chirp#91]
I think we should move the chirp* projects to adfinis-sygroup github and create pages hosted on adfinis-sygroup.ch as soon as they are stable. And use concretecloud just as incubator. My reasoning: it will convey the message, that chirp* is used and developed by Adfinis SyGroup more clearly.

Even if we have regular partner developers we can give them "admin" access using teams, so there is no technical downside to moving to adfinis-sygroup.

**Comment by keachi** [comment]
I think this is a good idea.
